apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-minikube
  labels:
    app: cv-minikube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cv-minikube
  template:
    metadata:
      labels:
        app: cv-minikube
    spec:
      containers:
      - name: cv-minikube
        image: shrikantdandge7/cv-minikube:116
        ports:
        - containerPort: 5000